### ISSUE TITLE
Reproducing results from the paper (Universal Dependencies)

### ISSUE THREAD

**Issue by andreasgrv** [yzhangcs/crfpar#2]
Hi, interesting paper and thank you for making this well structured code available.

I'm having trouble figuring out what to run to reproduce your results. More specifically, I've managed to load the Universal Dependencies dataset (v2.2) after making some changes to the corpus loading code, but I still have the following question:

* What configuration do I need to change to reproduce the comparison of LOC, CRF and CRF2O. Are second order features part of the released code?

Thanks in advance!

**Comment by yzhangcs** [comment]
Hi, thanks for your attention.
Currently I'm working to release the code as a python package, and the implementation of second-order model (i.e., CRF2O) has not been imported to this repository.
If you would like to try it for now, please refer to my another repo `yzhangcs/parser` and switch to the `release` branch.
I haved published the links of some pretrained models, you can download them and do some predictions & evaluations:
```py
>>> parser = Parser.load('crf-dep-en', verbose=False)
>>> parser.evaluate('parser/data/ptb/test.conllx')
(0.1680757158568927, UCM: 61.75% LCM: 50.83% UAS: 96.11% LAS: 94.50%)
>>> parser = Parser.load('crf2o-dep-en', verbose=False)
>>> parser.evaluate('parser/data/ptb/test.conllx')
(0.1394959150680474, UCM: 62.58% LCM: 51.24% UAS: 96.12% LAS: 94.53%)
```
To train the parsers from scratch, the commands are:
```sh
python -m supar.cmds.crf_dependency   train -b -d 0 -p <path>/model -f char --train <train-file> --dev <dev-file> --test <test-file> --embed <embedding-file> --unk <unk-in-embeddings> --mbr --proj
python -m supar.cmds.crf2o_dependency train -b -d 0 -p <path>/model -f char --train <train-file> --dev <dev-file> --test <test-file> --embed <embedding-file> --unk <unk-in-embeddings> --mbr --proj 


```
Feel free to ask me if you meet any issues.
