### ISSUE TITLE
关于论文Efficient Second-Order TreeCRF for Neural Dependency Parsing中的式子

### ISSUE THREAD

**Issue by ldsheng1998** [yzhangcs/crfpar#9]
您好，我想请教论文中与打分triaffine结构相关张量的shape形状
<img width="303" alt="Snipaste_2023-10-26_22-34-38" src="https://github.com/yzhangcs/crfpar/assets/129647771/ae83db73-f155-466b-a646-8e0114b957ca">
具体来说是我想请问：
您的论文中有说W(triaffine)的shape为（dxdxd），我想知道剩余三个部分的shape是怎样的，进而了解这三部分r(i)，r(k)，r(j)是如何与三阶的权重张量W进行相乘的。
期待您的回答，谢谢您！

**Comment by yzhangcs** [comment]
@ldsheng1998 Hi, 代码里我提供了一点注释
https://github.com/yzhangcs/parser/blob/main/supar/modules/affine.py#L227-L260

具体来说三个r都是`d * d`，方便计算会concat到大的`W`上

**Comment by ldsheng1998** [comment]
谢谢你我浏览了代码之后明白了您是如何计算的了
